name: padel_booking
description: A padel booking app
publish_to: "none"

version: 1.1.49+98

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  firebase_messaging: ^16.1.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  url_launcher: ^6.2.5
  package_info_plus: ^8.0.2
  store_redirect: ^2.0.4
  fl_chart: ^0.68.0
  intl: ^0.19.0
  image_picker: ^1.0.7
  firebase_storage: ^13.0.5
  http: ^1.2.0
  flutter_local_notifications: ^17.2.3
  flutter_svg: ^2.0.9
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4
  rxdart: ^0.27.7
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_app.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  # Make Android adaptive icon fill more space
  adaptive_icon_background: "#0A0E27"  # Dark blue background
  adaptive_icon_foreground: "assets/images/logo_app.png"
